// @codekit-append "vendors/dropkick.js"
// @codekit-append "vendors/spectrum.js"
// @codekit-append "vendors/moment.js"
// @codekit-append "vendors/pikaday.js"
// @codekit-append "vendors/pikaday.jquery.js"